# .ruff.toml  – top-level keys only
line-length = 88
target-version = "py312"          # match your CI interpreter
exclude = [".venv", ".git", "dist"]

[lint]
select = ["E", "F", "I", "B"]     # flake8-bugbear + default
ignore = ["E501"]                 # don’t fail on long lines

[format]
quote-style = "double"
