# .ruff.toml
[lint]
select   = ["E", "F", "I", "B"]       # keep same families
ignore   = ["B006"]                  # turn off mutable-default check
unfixable = ["B"]                    # don't try buggy auto-fixes

[lint.per-file-ignores]
"**/__init__.py" = ["F401"]          # allow re-exports

