name: “Auto-format with Ruff”
on:
  push:
    branches: [ main, 'release/**' ]
  pull_request:
    paths: [ '**/*.py' ]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install latest Ruff
        run: |
          python -m pip install --upgrade pip
          pip install 'ruff>=0.0.42'

      - name: Run Ruff lint autofixes
        run: |
          ruff check --fix .

      - name: Run Ruff formatter
        run: |
          ruff format .

      - name: Commit formatted code
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: apply Ruff formatting"
          file_pattern: "."
          author_name: github-actions
          author_email: actions@github.com
